/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 car.gltf --transform 
Files: car.gltf [44.92MB] > car-transformed.glb [3.55MB] (92%)
Author: toivo (https://sketchfab.com/toivo)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/car-scene-b7b32eaca80d460c9338197e2c9d1408
Title: Car Scene
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Car(props) {
  const { nodes, materials } = useGLTF('/car-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.car_body_body_0.geometry} material={materials.body} position={[40.507, 74.477, 0]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.car_body_rubber_0.geometry} material={materials.rubber} position={[40.507, 74.477, 0]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.car_body_glass_0.geometry} material={materials.glass} position={[40.507, 74.477, 0]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.door_left_interior_0.geometry} material={materials.interior} position={[60.954, 50.964, 72.077]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.number_plate_number_0.geometry} material={materials.number} position={[-122.792, 32.206, 0]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.wheel_00_wheels_0.geometry} material={materials.wheels} position={[-71.898, 25.337, 62.764]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.interior_01_chrome_0.geometry} material={materials.chrome} position={[55.23, 73.302, 0]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.lights_00_lights_0.geometry} material={materials.lights} position={[-113.307, 58.243, -52.905]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.chest_base_chest_0.geometry} material={materials.chest} position={[34.563, 137.34, 11.035]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.shadowplane_shadow_0.geometry} material={materials.shadow} position={[38.854, 0, 0.611]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.vintage_lantern_7_base_lantern_wall_base_2_0.geometry} material={materials.lantern_wall_base_2} position={[54.766, -2.068, -284.313]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.vintage_lantern_7_lantern_wall_base_1_0.geometry} material={materials.lantern_wall_base_1} position={[54.773, 197.266, -284.391]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.vintage_lantern_glass_7_lantern_wall_glass_1_0.geometry} material={materials.lantern_wall_glass_1} position={[55.011, 346.498, -277.111]} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/car-transformed.glb')
