/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 mac.gltf --transform 
Files: mac.gltf [590.79KB] > mac-transformed.glb [1.11MB] (-88%)
Author: Andreal3ast (https://sketchfab.com/Andreal3ast)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/n42284104a-mac-book-air-18f824369cbe4aaa84219e49c95fae9f
Title: N42284104A mac book air
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Mac(props) {
  const { nodes, materials } = useGLTF('/mac-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh  geometry={nodes['Sphere1031_Material_#12_0'].geometry} material={materials.PaletteMaterial001} position={[0.151, 0.005, 0.025]} rotation={[-1.548, 0, 0]} scale={0} />
      <mesh geometry={nodes['Object046_Material_#17_0'].geometry} material={materials.PaletteMaterial002} position={[0, 0.005, 0.006]} rotation={[-1.548, 0, 0]} scale={0.007} />

      <mesh geometry={nodes['Shape003_Material_#32_0'].geometry} material={materials.PaletteMaterial003} position={[0.018, 0.086, -0.106]} rotation={[Math.PI, 0, -Math.PI]} scale={0.001} />
    </group>
  )
}

useGLTF.preload('/mac-transformed.glb')
