/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 shoe.gltf --transform 
Files: shoe.gltf [8.91MB] > shoe-transformed.glb [4.69MB] (47%)
Author: Nevena Knežević (https://sketchfab.com/gavez)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/brothers-shoe-4268eb4870a045478cce51461f31a413
Title: Brothers shoe
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Shoe(props) {
  const { nodes, materials } = useGLTF('/shoe-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.material_0} position={[1.211, 0.986, 8.313]} rotation={[Math.PI / 2, 0, -Math.PI]} />
    </group>
  )
}

useGLTF.preload('/shoe-transformed.glb')
